#!/bin/bash
#
#Php7.2 paigaldamine
#
#Kontrollib kas php7.2 teenus on paigaldatud

#------------------

php=$(dpkg-query -W -f='${Status}' php7.2 2>/dev/null | grep -c "ok installed")

 echo $php

#Tulemuseks saab 0 või 1
#Kui tulemus on 0 siis pole paigaldatud ja peab paigaldama
#
if [ $php -eq 0 ]; then
	echo "Paigaldame php7.2"
apt update

apt upgrade
#-------Enable PPA
apt install -y apt-transport-https lsb-release ca-certificates
wget -O /etc/apt/trusted.gpg.d/php.gpg https://packages.sury.org/php/apt.gpg
echo "deb https://packages.sury.org/php/ $(lsb_release -sc) main" > /etc/apt/sources.list.d/php.list
apt update
#--------Install PHP 7,2
	apt install -y php7.2;
	apt search php7.2;
	apt install -y  php7.2 php7.2-cli php7.2-common php7.2-json php7.2-opcache php7.2-mysql php7.2-zip php7.2-fpm php7.2-mbstring
#Kui ridade arvu tulemuseks on 1, siis ei pea paigaldama
elif [ $php -eq 1 ]; then
	echo "php7.2 on paigaldatud!"
	#Näitab staatust
	php -v
fi
